### ISSUE TITLE
Does Not Support TCP keepalive

### ISSUE THREAD

**Issue by Aloksmvdu** [mortzdk/Websocket#3]
In this server it does not provide tcp keepalive option. It uses system default configuration so if a client crash/power off then server does not know about this event.

**Comment by mortzdk** [comment]
As of version 2.0.0 this should no longer be an issue.

If a client shuts down, the server will now delete it from the internal session list. Furthermore it is now possible to define a timeout, such that inactive clients are dropped.

I'll close this issue.
