### ISSUE TITLE
Internet Explorer 11 incorrectly breaks off connection each 15 seconds

### ISSUE THREAD

**Issue by aicoliu** [mortzdk/Websocket#5]
Internet Explorer 11 Will break off  the websocket connection.

please help to check.

[https://github.com/hoaproject/Websocket/issues/33](url)

Here is what need to be considered.

IE sends an unsollicited PONG frame. The RFC6455 says:

A Pong frame MAY be sent unsolicited. This serves as a
unidirectional heartbeat. A response to an unsolicited Pong frame is
not expected.

Several implementations out there (Play, Spring, Go etc.) encountered this issue because receiving an unsollicited PONG was not expected and was creating a bug. In Hoa\Websocket, this is not the case because we handle it as required by the RFC. IE has the fin parameter set to 1, not 0, so this is a valid frame and we don't respond to it.

Since we don't respond, IE sends a random frame that is not a valid one. And yes, random, I don't receive the same frame twice.
After some searches, it seems that this is a known bug in IE10 (not 11). To fix that, we may return a PING. This is what I did, but it does not fix anything. Maybe on IE10, but not on IE11.

Because the bug is still opened on IE10, we can assume this is still present in IE11.

I close this issue because I can't do anything to avoid that… The connection is closed by the server because of the malformed/invalid message we receive after the PONG. IE does not fire the CloseEvent properly despites the server sends a valid close frame!

Sorry for that. If you find a server that handles IE11 properly, I would be glad to know them and look inside the code to see what workaround they found.

**Comment by mortzdk** [comment]
As of version 2.0.0 this should no longer be an issue.

IE 11 sends an unsolidated PONG frame each 15 seconds, which we now handle simply by ignoring it.

I have not been able to reproduce the behaviour mentioned about IE sending a random invalid frame afterwards.

I'll close this issue for now.
